# Prose Pod API
# REST API for administrating a Prose Pod
# Configuration file
# Example: https://github.com/prose-im/prose-pod-system/blob/master/Prose-example.toml
# All keys: https://github.com/prose-im/prose-pod-api/blob/master/crates/service/src/features/app_config/mod.rs

[branding]
page_url = "https://admin.prose.org/"
company_name = "Prose"

[notify.email]
from = "pod@prose.org"
to = "pod@prose.org"

smtp_host = "localhost"
smtp_port = 587
smtp_username = "user-access"
smtp_password = "user-password"
smtp_encrypt = false

[debug_only.dependency_modes]
notifier = "logging"
